# Generated by Django 4.2.15 on 2024-09-04 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("twitter", "0002_profile_date_modifield"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="date_modifield",
            new_name="date_modified",
        ),
    ]
